### PR TITLE
check_fortigate.pl - added uptime, license, linkstatus, conserve, fortimanager health , fortimanager devicestatus

### PR DESCRIPTION
**Pull request by sgruber94**
- added: FortiManager Health Checks (cpu, mem, disk)
- added: FortiManager Health Checks for connected devices health (up/down) and config-sync State (fmgdevice)
- added: Fortigate Uptime warn (behaviour if warn is set)
- added: Fortigate License expiration Check monitoring for FortiGate with critical & warning (license)
- added: Fortigate License Version Check for scheduled Updates on FortiGate (license-version)
- added: Link-Monitor Health Check (alive,dead), tested on Forti900D running FortiOS 6.4.5, Forti60F 6.4.5
- added: FortiGate conserve mode for proxy and kernel (conserve-proxy , conserve-kernel)
- fixed: typo in SD-WANHealth

### CODE REVIEW

**Comment by sgruber94** [comment]
Did you need any additional information about the change? 

If so, please give me the needed information :)  @riskersen 

cheers
Sebastian

**Review by riskersen — CHANGES_REQUESTED** [review]
Could you please rebase your changes against the current version?

**Comment by sgruber94** [comment]
> Could you please rebase your changes against the current version?

Increment the version of the script.

**Review by riskersen — APPROVED** [review]

**Comment by riskersen** [comment]
Thanks!

**Pull request merged**
