### PR TITLE
Update check_fortigate.pl

### PR DESCRIPTION
**Pull request by arigaud**
Just because selected types of device are available only when reading source code

Perhaps they have their place in help mode too.

### CODE REVIEW

**Comment by riskersen** [comment]
Hi Alexandre,

many thanks again.

I'm curious why do you need to exclude synchronization check for the cluster check?

BR
Oliver

**Comment by arigaud** [comment]
Hi Oliver !

I knew this what going to provoke your curiosity 😁

So we manage several hundred fw on my company. For 5 of them Sync status is unsynchronized (oid result) but all checks commands are ok.

We have opened a technical support request.

**Comment by riskersen** [comment]
Interesting..even recalculating the checksum didnt solve the issue?

But in any case, thanks again for the contribution.

Am 07.07.2017 20:30 schrieb "Alexandre Rigaud" <notifications@github.com>:

Hi Oliver !

I knew this what going to provoke your curiosity 😁

So we manage several hundred fw on my company. For 5 of them Sync status is
unsynchronized (oid result) but all checks commands are ok.

We have opened a technical support request.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/riskersen/Monitoring/pull/38#issuecomment-313759236>,
or mute the thread

**Comment by arigaud** [comment]
Nope oid result indicate master Sync is ok but not for the slave.

Global checksum we Can see on oid .15 are similar (master/slave).

All confs are the same, support maybe help us

**Pull request merged**
